# Header
menu:
  Home: /
  Archives: /archives
rss: /feed/

# Content
excerpt_link: Lees verder
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-49291515-1
#favicon: /favicon.png
twitter: webstack_nl
google_plus:
fb_admins:
fb_app_id:
